dist: bionic
# The following enables several GHC versions to be tested; often it's enough to
# test only against the last release in a major GHC version. Feel free to omit
# lines listings versions you don't need/want testing for.
env:
  - CABALVER=2.4 GHCVER=7.6.3
  - CABALVER=2.4 GHCVER=7.8.4
  - CABALVER=2.4 GHCVER=7.10.3
  - CABALVER=2.4 GHCVER=8.0.2
  - CABALVER=2.4 GHCVER=8.2.2
  - CABALVER=2.4 GHCVER=8.4.4
  - CABALVER=2.4 GHCVER=8.6.5
  - CABALVER=3.0 GHCVER=8.8.3
  - CABALVER=3.0 GHCVER=8.10.1
# - CABALVER=head GHCVER=head   # see section about GHC HEAD snapshots

# Note: the distinction between `before_install` and `install` is not important.
before_install:
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -qq --yes libcwiid-dev libsdl1.2-dev libsdl-gfx1.2-dev libbluetooth-dev libsdl-ttf2.0-dev
  - travis_retry sudo apt-get install --yes cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - cabal --version
  - ghc --version
  - travis_retry cabal update

script:
  - cabal new-build all && cabal new-test all

install:
  - skip

# This step requires the use of edge: true in deploy. For details, see
# https://docs.travis-ci.com/user/deployment-v2
before_deploy:
  - cd dunai/

deploy:
  edge: true
  provider: hackage
  username: keera_studios_ci_dunai
  password:
    secure: nfxBR6dV3B+qmQcxiJsmQMPrRUvUZRfSPmhFWwFIjJCfjJLTteQg9V0QI2IpssnNos9qQrCF9qxsvSGSliC9rANYRz8jGz4y5/8XmS0LE71BDTvB8WyzWhKGB9SXNN4xozEIvFDdpEopeK3uh7yf3GXY30zDNhYbZaj38eUF0/3WfxcBBgKDjPgnVShNgoXkkwI6Vz+e1M42/f0IoUVdXWikmCuczMoVYKIkawr+qjCKn9jzKzsdxVYgFtKwOx4wzXvncfvsi1H90pHt4RZi0ufS0qhFxq8Wylx8s1J4i1AuC/2iuAhdEOTidSXGUpi3hDfPhvq70+5vJr9RxgdRA5SkqXT/cck5cC21uOuIw1mGs2Zic7jD16MrpDmZEgZq5QpsK7Hwy5B3+YXZ7y7gG8nxobg8Fj49IbYTuigGrlXJumAXMtU1mspRfWthySKLLrVyCqn8Jow8DcjtmQDGRf4yY2EPngf8iJ7VmFaUpiCPZZ2aE4FxjSpqgJLFun2szLsNLNVFkUHjHF/NFJzW6i+evy/oJmvk+SmI0D/YunbUmlgrN2+sy5TpwWquN9I78SDaGpP8yNlR7OutU6DgLpu9BigLTQHKQr+tJz30c4em3w2Gl1F+QM8sIEEvafEX8+h6WqpKuHi8sQlJKJziAnoEfgDC83tKJJpMc9hj3kE=
  on:
    branch: master
    condition:
      - ${TRAVIS_HASKELL_VERSION}=8.6.5
